default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pick_em_up_development

test:
  <<: *default
  database: pick_em_up_test

production:
  <<: *default
  database: pick_em_up